### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by HeartyYF**
Please don't merge it at once, please tell me
```
achievement.an.hedgehogsonic=Gotta Go Fast!
achievement.an.hedgehogsonic.desc=Discover Sonic
achievement.an.hedgehogsanic=No Go Fastr!!!
achievement.an.hedgehogsanic.desc=Cumon Step it Up!!
```
What's the meaning exactly, I'll write them in...

### CODE REVIEW

**Comment by capnkirok** [comment]
Ah yes, these are Easter Egg achievement srelated to Sonic the Hedgehog.

Hard to translate as they are based on memes... of very silly drawings

Here is an example:

 

You could probablt just translate:

Sonic the Hedgehog
Discover Sonic

Sanic the Hedhehog
Discover Sanic

**Comment by HeartyYF** [comment]
I'm just wondering what's No Go Fastr!!! and what's Cumon Step it Up!!
Maybe it is just faster?

**Comment by capnkirok** [comment]
Yeah, intentional misspellings, again... meme

No, go faster
Come on, step it up (basically: try harder)

**Comment by HeartyYF** [comment]
@TartaricAcid Make a check, please

**Comment by TartaricAcid** [comment]
Thanks for your translation.

**Pull request merged**
