### PR TITLE
Created locale file for Danish (da_DK.lang)

### PR DESCRIPTION
**Pull request by Zerotiger**
Finished the translation to Danish as I said I would in the following tweet:
https://twitter.com/TheZerotiger/status/831481566551474176

If translators are featured in any credit sections, I'd like to be listed as Ruukas (perhaps linking to this https://minecraft.curseforge.com/members/Ruukasu)

### CODE REVIEW

**Comment by Zerotiger** [comment]
I have a few corrections to make, but it doesn't seem like I am able to make them until the branches have been merged.

**Comment by Crisefelia** [comment]
I have worked a bit on translating it, myself. Suggesting changing some of the English pig breed names:

Old Spot -> Gloucester (from Gloucestershire Old Spot, the full breed name)
Large Black -> Devon (Large Black/Devon Pig is called "Large Black" in Danish Breeders literature. It does not get translated to "Stor Sort", not to mention the trouble with the potential confusion between "sort = black" and "sort = type/race/breed".) (Danish is merciless.)
Large White = Amerikansk Yorkshire ("=American Yorkshire". Both Yorkshire and Large White are technically of the Yorkshire breed, the Large White is derived from the Yorkeshire. In Danish, they seem both to be called "Yorkshire", hence the need for English vs. American.)

Frisian -> Frieser (Not too happy with this. Frieser is most often used for a Holsteiner-patterned HORSE, not cattle. There is no real name for it in Danish, as Frisian refers to the European stock of Holstein cattle, whereas "Holstein" is used to refer to the US stock. Same breed, two different names depending on where they came from. In Denmark, a Holstein would be a Holstein-Frieser, as we have crossbred them.)
Longhorn -> Texas Langhorn (And yes, "Langhorn" is awkward-sounding. Danish "langhorn" refers to either Texas Longhorn or Scottish Longhorn, hence the need for the distinction. Those two breeds look nothing alike, after all.)
Chickens! Many, many chicken breeds actually keep their English names in Danish, the exceptions of:
Leghorn -> Italiener (Literally "Italian [the noun]" - because Leghorns stem from Tuscany, they are called "Italians" in Danish.)
Wyandotte -> Wyandotter (Classic example of a loan-word being Danish-fied with an "-er" postfix.)

As a quick sidenote: "Fritte" is a white or albino Ilder, not a species unto itself.
(Making "Grå Fritte" an oxymoron.)
But "Ilder" is a cumbersome and awkward name, so I support the use of "Fritte".

[Animania_Da_DK_Crisefelia.txt](https://github.com/capnkirok/animania/files/775069/Animania_Da_DK_Crisefelia.txt)

**Comment by Crisefelia** [comment]
Another quick sidenote: "Plain Omelette" could be changed to "Simpel Omelet", as the current suggestion of "Enkel Omelet" could be read as "Single Omelet", seeing as the Danish word "enkel" can mean both simple and single.

**Comment by Zerotiger** [comment]
I'll make the changes you suggested, thank you 👍 
I was considering "Simpel Omelet", but I thought "Enkel Omelet" was a more accurate translation. I don't think people will confuse it with single, when there is a stacksize number, unless they are doing it on purpose.

**Pull request closed without merging**
